# Generated by Django 2.1.3 on 2018-12-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id_graph', models.AutoField(db_column='ID_Graph', primary_key=True, serialize=False)),
                ('images_graph', models.ImageField(db_column='Images_Graph', upload_to='')),
            ],
            options={
                'db_table': 'Graph',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matrixsize',
            fields=[
                ('id_km', models.AutoField(db_column='ID_KM', primary_key=True, serialize=False)),
                ('id_k', models.IntegerField(db_column='ID_K')),
                ('id_m', models.IntegerField(db_column='ID_M')),
            ],
            options={
                'db_table': 'MatrixSize',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nu',
            fields=[
                ('id_nu', models.AutoField(db_column='ID_Nu', primary_key=True, serialize=False)),
                ('value_nu', models.FloatField(db_column='Value_Nu')),
            ],
            options={
                'db_table': 'Nu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id_q', models.AutoField(db_column='ID_Q', primary_key=True, serialize=False)),
                ('value_q', models.FloatField(db_column='Value_Q')),
            ],
            options={
                'db_table': 'Q',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='R',
            fields=[
                ('id_r', models.AutoField(db_column='ID_R', primary_key=True, serialize=False)),
                ('value_r', models.FloatField(db_column='Value_R')),
            ],
            options={
                'db_table': 'R',
                'managed': True,
            },
        ),
    ]
