# Generated by Django 2.1.3 on 2018-12-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20181205_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_Log',
            fields=[
                ('id_log', models.AutoField(db_column='ID_Log', primary_key=True, serialize=False)),
                ('User_log', models.CharField(db_column='Name_User', max_length=50)),
                ('Date_log', models.DateTimeField(db_column='Date')),
                ('Valeu_log', models.FloatField(db_column='Value')),
            ],
            options={
                'db_table': 'Log',
                'managed': True,
            },
        ),
    ]
