# Generated by Django 2.1.3 on 2018-12-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_table_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_log',
            name='User_log',
        ),
    ]
